//------------------------------- -*- C++ -*- -------------------------------//
// Copyright Celeritas contributors: see top-level COPYRIGHT file for details
// SPDX-License-Identifier: (Apache-2.0 OR MIT)
//---------------------------------------------------------------------------//
//! \file JsonEventReader.hh
//---------------------------------------------------------------------------//
#pragma once

#include <fstream>
#include <string>

#include "Primary.hh"

//---------------------------------------------------------------------------//
/*!
 * Read file generated by \c JsonEventWriter .
 */
class JsonEventReader
{
  public:
    //!@{
    //! \name Type aliases
    using result_type = std::vector<Primary>;
    //!@}

    // Construct with filename
    JsonEventReader(std::string const& filename);
    ~JsonEventReader() = default;

    // Read a single event from the json file
    result_type operator()();

    //! Get total number of events
    unsigned int num_events() const { return num_events_; }

  private:
    std::ifstream infile_;
    unsigned int num_events_{0};
};
